### ISSUE TITLE
Don't work execute-file function on windows

### ISSUE THREAD

**Issue by cagechi** [obaland/vfiler.vim#11] opened 2023-03-13 13:01 UTC
`execute-file` function is same xyzzy's `shell-execute` ?

ps. tell me how to show 2-windows-layout

**Comment by obaland** [comment] 2023-03-13 13:39
The `execute-file` action executes a file as an external program.
For example, an `.xlsx` file executes an Excel program, unlike xyzzy's `shell-execute` action.

Also, the way to launch the two windows is to use the `Tab` key in the default key bindings. Once launched, you can use the `Tab` key to move between windows.

Your feedback is welcome.

**Comment by cagechi** [comment] 2023-03-13 14:15
Thank you for reply.
But when I select the xlsx file and press 'x' nothing happens.

Thank you!! When I press the Tab key, it became 2windows. 
But pressing the 'C' key does not copy to another window,
copied to the clipboard
When press the 'cc' key, got an error `Failed to copy "filename"`

**Comment by obaland** [comment] 2023-03-14 00:19
Thank you for your response.
Sorry for any inconvenience caused.

I will investigate the following two issues.
1. `copy` action fails.
2. The `execute_file` action does not work.

I will investigate `1.` first.
`2.` may take some time.

Please keep your help in the future.

**Comment by obaland** [comment] 2023-03-24 11:51
@cagechi 
Thank you for your patience.
`execute-file` action has been fixed (https://github.com/obaland/vfiler.vim/commit/073601a5336f82b8ff9fb85fe9a4874ac2e5c337). This should improve things, so could you please give it a try?

Also, have added a note to the documentation about the 2-screen filer (https://github.com/obaland/vfiler.vim/commit/929bc2a4f1daed54a199008f9deddb4dce1bcbe7).
I hope this will be helpful.

Best regards.

**Comment by cagechi** [comment] 2023-03-24 14:06
I checked it, but the result does not change.
###  copy action
 1. execute vfiler
 2. press the `Tab` key -> become 2-window layout
 3. press the `Space` key for marking
 4. press the `C` key then `Copy to the clipboard` message is displayed.
 5. press the `CC` key then `Failed to copy` message is displayed.

### execute-file
 press the `x` then nothing happens.

**Comment by obaland** [comment] 2023-03-25 02:03
Thank you for your report.

Sorry. I do not know immediately.
Let me check a few things in order to match our environment as much as possible.

1. OS is Windows, right?
2. Neovim or Vim?
3. How are you running (Neo)vim? (e.g. Powershell, cmd, or GUI, etc.)

By the way, in the case of `vfiler.vim`,
if you are using a 2-window filer, you can copy the selected file to the other one by just `cc`.

**Comment by cagechi** [comment] 2023-03-27 07:09
The environment is as follows

1. Windows 10, Windows 11
2. Neovim v0.8.3
3. PowerShell(7.3.3) + nvim , goneovim(0.6.4)

> if you are using a 2-window filer, you can copy the selected file to the other one by just cc.

I am sorry. I wrote it incorrectly.
The correct expression is "press the `cc` key then `[vfiler]: Failed to copy` message is displayed."

**Comment by obaland** [comment] 2023-03-27 12:38
Thanks for the information.

Let me check one more thing just to be sure.
The file you are trying to copy or executing is,
`protected operating system file`, is it not?

**Comment by cagechi** [comment] 2023-03-27 13:14
Thank you for fast response.

> protected operating system file, is it not?

No, It's normal file.
For example `~/hoge.txt`

**Comment by obaland** [comment] 2023-03-27 13:18
Thank you for your response.

I will investigate based on the information you provided and will contact you as soon as make progress.
If you have any other insights, it would be greatly appreciated.

Best regards.

**Comment by obaland** [comment] 2023-03-31 11:03
@cagechi 
Sorry, I trying to determine the cause of the problem, but are having difficulty.
If you don't mind, could you please let me know the configuration of Neovim?

**Comment by cagechi** [comment] 2023-03-31 11:43
I have checked all the settings.
Apparently, there was a problem with the shell options.
I disabled the shell options and vfiler worked fine.
`-- vim.opt.shell = 'pwsh.exe'`

I will disable it and operate it for now.
Thank you very much for your help.

**Comment by obaland** [comment] 2023-04-01 02:52
Thanks for providing valuable information.

I have modified it so that it does not depend on the `sell` option. (https://github.com/obaland/vfiler.vim/commit/f554e95db7fee9c17c03daaa5301a89d0af52fa9)
Please give it a try.

**Comment by cagechi** [comment] 2023-04-01 04:01
I tried it.
Function `copy` and `move` worked fine, but function `execute-file` did not work.

**Comment by obaland** [comment] 2023-04-04 03:53
Thank you again and again for your cooperation.
I have corrected the apparent cause of the problem. (https://github.com/obaland/vfiler.vim/commit/d5a2deaa56adc519b2c2fac01456edbad885b8af)

Please give it a try.

**Comment by cagechi** [comment] 2023-04-04 11:41
Function `execute-file` worked fine!!
Thanks for fixing it.

**Comment by obaland** [comment] 2023-04-04 11:54
Thanks to your help, have a better product.
Thank you for your cooperation.

**Comment by obaland** [comment] 2023-04-04 12:01
@cagechi 
I will close it.
Please contact us if you have any problems.

**Closed as completed by obaland** 2023-04-04 12:01 UTC
Labels: bug, question
